# Generated by Django 4.2 on 2023-04-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kids',
            new_name='kidsitem',
        ),
        migrations.RenameModel(
            old_name='vegitables',
            new_name='vegetables',
        ),
    ]
