# Generated by Django 4.2 on 2023-04-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_rename_kids_kidsitem_rename_vegitables_vegetables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruits',
            name='name',
        ),
        migrations.RemoveField(
            model_name='kidsitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vegetables',
            name='name',
        ),
    ]
