# Generated by Django 4.2 on 2023-04-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fruits',
        ),
        migrations.DeleteModel(
            name='kidsitem',
        ),
        migrations.DeleteModel(
            name='vegetables',
        ),
    ]
