# Generated by Django 4.2 on 2023-04-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruits',
            old_name='rete',
            new_name='rate',
        ),
    ]
